--!Ups
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE "USERS"(
    "ID"        UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    "USERNAME"  VARCHAR(20) UNIQUE,
    "PASSWORD"  VARCHAR(255)
);

CREATE TABLE "USERS_AUTH"(
    "ID_USERS"      UUID PRIMARY KEY REFERENCES "USERS"("ID"),
    "ATTEMPT_AT"    TIMESTAMP DEFAULT NOW(),
    "IS_SUCCESS"    BOOLEAN,
    "IP_ADDRESS"    VARCHAR(20)
);

--!Downs 
DROP TABLE "USERS_AUTH";
DROP TABLE "USERS";
DROP EXTENSION "uuid-ossp";